[build]
  command = "npm run build" # O 'yarn build' si usas Yarn
  publish = "build"

[functions]
  directory = "netlify/functions" # Directorio donde se generará la función serverless de Remix

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200