[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"     # Para funciones estándar
  edge_functions = "netlify/edge"     # Para Edge Functions

# Para Edge Functions (opcional)
[[edge_functions]]
  function = "server"
  path = "/*"

# Para funciones estándar
[functions]
  node_bundler = "esbuild"